(require-package 'diminish)
(diminish 'anzu-mode)
(diminish 'guide-key-mode)
;;(diminish 'highlight-symbol-mode)
(diminish 'google-this-mode)
(diminish 'workgroups-mode)
(diminish 'projectile-mode)
(diminish 'eldoc-mode)
(diminish 'auto-complete-mode)
(diminish 'whole-line-or-region-mode)
(diminish 'yas-minor-mode)
(diminish 'abbrev-mode)
(diminish 'global-visual-line-mode)

(provide 'init-diminish)
